Update icde.yml
ccfddl/ccf-deadlines pull request #109
Opened 2022-04-11 06:29 UTC by Zeng1998

### Which conference does this PR update?

-

### Related URL

-

2022-04-11 06:36 UTC, cubercsl requested changes

2022-04-11 06:36 UTC, cubercsl commented on conference/DB/icde.yml
> +      date: April 3–7, 2023
```suggestion
      date: April 3-7, 2023
```

2022-04-11 06:38 UTC, cubercsl commented on conference/DB/icde.yml
> +        - deadline: '2021-04-25 23:59:59'
Why the deadline is `2021` ?

2022-04-12 03:38 UTC, jacklightChen approved these changes

2022-04-12 03:39 UTC, merged