IUI 2024
ccfddl/ccf-deadlines pull request #304
Opened 2023-09-18 01:46 UTC by gusongen

### Which conference does this PR update?

- IUI 2024

### Related URL

-

2023-09-18 05:37 UTC, ViGeng requested changes
I suppose the conf time is in March?

2023-09-18 05:37 UTC, ViGeng commented on conference/HI/iui.yml
> +      date: May 18 - May 21, 2024
I think it's between 18-21 `March`?

2023-09-18 05:45 UTC, ViGeng commented on conference/HI/iui.yml
> +      date: May 18 - May 21, 2024
updated.

2023-09-18 05:48 UTC, merged

2023-09-19 05:17 UTC, gusongen commented
> I suppose the conf time is in March?

You are right, thx for correction !