Update DSN 2024
ccfddl/ccf-deadlines pull request #326
Opened 2023-10-24 04:10 UTC by grandnew

### Which conference does this PR update?

- DSN 2024

### Related URL

- https://dsn2024uq.github.io/dates.html

2023-10-24 04:36 UTC, ViGeng commented on conference/SC/dsn.yml
> +- title: DSN
please only add a year entry rather than a conf entry

2023-10-24 04:37 UTC, ViGeng requested changes
<img width="875" alt="image" src="https://github.com/ccfddl/ccf-deadlines/assets/31836829/b7ecfea1-6a25-410f-98cd-d0831b4d3d28">
Hi, thanks for your contribution! 
please only add a year entry.

2023-10-24 15:04 UTC, grandnew commented
@ViGeng Fixed.

2023-10-25 02:31 UTC, ViGeng approved these changes

2023-10-25 02:37 UTC, merged