OSDI 2025
ccfddl/ccf-deadlines pull request #629
Opened 2024-09-04 12:17 UTC by sirius0118

### Which conference does this PR update?

- OSDI 2025

### Related URL

- https://www.usenix.org/conference/osdi25/call-for-papers

2024-09-04 14:35 UTC, ViGeng approved these changes
LGTM

2024-09-04 14:39 UTC, ViGeng requested changes
it seems the abstract ddl should be 12-03?

2024-09-05 01:54 UTC, sirius0118 commented
I have updated the abstract DDL to 12-03

2024-09-05 09:17 UTC, ViGeng approved these changes

2024-09-05 09:18 UTC, merged